### ISSUE TITLE
Feature Request: Add ability to extend DEFAULT_FORBIDDEN_XXX / DEFAULT_WARNED_XXX

### ISSUE THREAD

**Issue by sebastiaanspeck** [StevenLooman/sonar-magik#120]
Right now, if you have forbidden-call.forbidden-calls in your properties-file, it will only include those calls.
Could we maybe split those properties into forbidden-call.forbidden-calls and forbidden-call.extended-forbidden-calls?

That way you also get the default forbidden calls (even if new ones get added later on) and also your own. We could also argue if that should be the default behaviour.

**Comment by StevenLooman** [comment]
No. This will make things more complex. If you upgrade, you should know what has changed and not blindly upgrade.
