### ISSUE TITLE
When setting UnusedVariableCheck.checkParameters to true, abstract methods are checked as well

### ISSUE THREAD

**Issue by sebastiaanspeck** [StevenLooman/sonar-magik#123]
```magik
_abstract _method a.b(p_param1)
_endmethod
```

This snippet raises an issue on p_param1 that it is unused, but an abstract method will always be empty. IMO it is a good habit to show in the abstract method which parameters the subclass needs to implement.

#122 implements this behaviour.

**Comment by StevenLooman** [comment]
Agreed.
