### ISSUE TITLE
Using `--apply-fixes` with `_pragma` results in weird code

### ISSUE THREAD

**Issue by sebastiaanspeck** [StevenLooman/sonar-magik#138]
When having this snippet, there is an issue that between `$` and `_pragma...`, there should be a newline.

```
_package user

def_slotted_exemplar(:a, {})
$
_pragma(classify_level=restricted, topic={magik_lint})
_method a.b
	## Do something that returns :b
	##
	>> :b
_endmethod
$
```

When running the `magik-lint` with `--apply-fixes`, it becomes:
```
_package user

def_slotted_exemplar(:a, {})
$_pragma(classify_level=restricted, topic={magik_lint})
_method a.b
	## Do something that returns :b
	##
	>> :b
_endmethod
$
```

If I remove the `_pragma` and have `_method` on the next line, it won't format anyway.

Even if I run it with `--apply-fixes` on the next snippet, it will result in the weird code:
```
_package user

def_slotted_exemplar(:a, {})
$

_pragma(classify_level=restricted, topic={magik_lint})
_method a.b
	## Do something that returns :b
	##
	>> :b
_endmethod
$
```

**Comment by StevenLooman** [comment]
I think this is fixed with https://github.com/StevenLooman/magik-tools/commit/68d1acdcb69072b01ff79798237911780cd94012. Can you confirm this?

**Comment by sebastiaanspeck** [comment]
It does! 💯 it also removes any extra newlines now 😃

**Comment by sebastiaanspeck** [comment]
I found another three anomalies;

```
_proc()
```

Becomes
```
_proc ()
```

And 

```
_loop@label
```

Becomes

```
_loop @label
```

The last one is related to indentation:
```
	>> _if _true
	   _then >> 1
	   _endif.default(2)
```

Becomes
```
	>> _if _true
	_then >> 1
	_endif.default(2)
```

~I do not know if this is desired behaviour.~ If I revert the indentation-changes, the linter triggers on "improper indenting".

```
_pragma(classify_level=basic)
def_slotted_exemplar(:person,
		     {
			     {:name, _unset},
			     {:date_of_birth, _unset}
		     })
$
```

Should be
```
_pragma(classify_level=basic)
def_slotted_exemplar(:person,
	{
		{:name, _unset},
		{:date_of_birth, _unset}
	})
$
```

But I use tree-sitter which resolves the indentation to the first code snippet.
