### ISSUE TITLE
Raise an issue for multiple newlines

### ISSUE THREAD

**Issue by sebastiaanspeck** [StevenLooman/sonar-magik#39]
```
1 _package user
2 
3 
4 def_slotted_exemplar(:a, {})
5 $
6 
7 _method a.b()
8 _endmethod
9 $
10 
11 _method a.c()
12 	a.do_something()
13 _endmethod
14 $
15
16
17 _method a.d
18 _endmethod
19 $
20 
21 
22 _method a.e
23 	a.do_something_else()
24 _endmethod
25 $
```

Looking at the code snippet above, it would be nice if the `magik-lint` would raise issues for multiple newlines on lines 3, 16 and 21. A single newline is sufficient for Magik. Extra newlines only creates clutter and doesn't encourage a uniform code style.

**Comment by StevenLooman** [comment]
Thank you for reporting this @sebastiaanspeck!

Merged, to be included in a future release.
