### ISSUE TITLE
Error installing plugin

### ISSUE THREAD

**Issue by jasonhullinger** [StevenLooman/sonar-magik#4]
After placing the plugin into extensions/plugins/ I'm getting the following error when restarting SonarQube:

Caused by: java.io.IOException: Resource not found in the classpath: org/stevenlooman/sw/sonar/l10n/magik/rules/VariableDeclarationUsageDistance.html

**Comment by StevenLooman** [comment]
Thank you for this issue. I'll try to look into it this weekend.

**Comment by StevenLooman** [comment]
Which version of the extension/plugin are you using? It is best to use [0.4.0](https://github.com/StevenLooman/sonar-magik/releases/tag/0.4.0) for now. Using SonarQube `7.9.5` I do not see any errors.

I am working on a new version, but this is not ready to be released yet. It will contain several improvements, but also shifts the main focus from SonarQube to the linter and other parts. Still, SonarQube will still be supported.
