### ISSUE TITLE
Adding `# mlint disable=<check-name>` to top of the file is broken since 0.8.0

### ISSUE THREAD

**Issue by sebastiaanspeck** [StevenLooman/sonar-magik#42]
As the title already says, adding `# mlint disable=<check-name>` to top of the file is broken. It worked fine until 0.7.1, but currently it is still broken, even on the latest version of develop.

**Comment by StevenLooman** [comment]
Thank you for reporting this. It should be fixed now.

**Comment by sebastiaanspeck** [comment]
It is fixed 💯
